# Generated by Django 5.0.2 on 2024-07-07 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="store_categ_name_1278fd_idx",
        ),
    ]
